# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('from_number', models.IntegerField()),
                ('to_number', models.IntegerField()),
                ('sent', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=True)),
                ('error', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
