# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='received',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent',
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
