# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171021_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='google_image_result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='animal',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
