# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171021_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
