# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='clean',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='dirty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='dog_breed',
            field=models.IntegerField(blank=True, choices=[(1, 'Golden Retriever')], null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='dog_breed_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='emotion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='emotion_type',
            field=models.IntegerField(blank=True, choices=[(3, 'Aloof'), (1, 'Angry'), (2, 'Scared'), (4, 'Friendly')], null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
