# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171021_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='dog_breed',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='dog_breed_name',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='emotion_type',
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
