# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-21 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171021_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
